download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/nutanix-ncp-2.5.0.tar.gz
format_version: 1.0.0
name: ncp
namespace: nutanix
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.5.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/nutanix/ncp/versions/2.5.0/
